### PR TITLE
stream already been listened to when user clicked on their second conversation

### LINKED ISSUE #205: stream already been listened to when user clicked on their second conversation
This was that I was not able to click another conversation once I clicked into the first. I instinctively started to think it was the _controller being reused for all conversations.

Screen Shot 2020-07-05 at 5 58 29 pm

### LINKED ISSUE #208: Error when no messages exists within a conversation
Got the following error on a conversations with no messages.

```dart
Exception has occurred.
StateError (Bad state: No element)
```

Screen Shot 2020-07-05 at 8 18 24 pm

One possible solution is to not init prematurely and instead change the algorithm so it the first message will pick up as the first. In python I'd init the algorithm to start with `datetime.min()` which is the first possible value of a datetime.

### PR DESCRIPTION
**Pull request by gaslitbytech**
This is a impulsive fix to a issue that I found while creating a new feature. This was that I was not able to click another conversation once I clicked into the first. I instinctively started to think it was the _controller being reused for all conversations. I almost didn't get this far as I accidently did the fix initially within `_database.getMessagesStream(conversationId).listen((messagesList) {` inner function? And When I tried to return the `_controllers[conversationId].stream I'd get a null exception as the changes within this inner function I suppose it was that it was not in scope. Anyway this seems to work and fixes the bug. I'll add a issue to track this bug now.

### CODE REVIEW

**Comment by nickmeinhold** [comment]
Hey mate, I attempted to start a discussion in #205 - I think it's worth discussing our approach to managing the streams - keeping a stream controller for each conversation is certainly one option - my instinct is that there are better options but I would be happy to have my mind changed.  My suggestion would be that we take the time to talk it through as it will be educational and we can explore advantages and disadvantages of each approach.  If that's frustrating please do let me know so we can try and find a way forward that works for us both. Thanks! :-)

File: lib/services/database_service.dart [hunk 1]
```diff
@@ -12,15 +12,24 @@ import 'package:adventures_in_chat_app/extensions/extensions.dart';
...
+    if (_controllers.containsKey(conversationId)) {
+      _controller = _controllers[conversationId];
+    } else {
+      _controller = StreamController<List<MessagesListItem>>();
+    }
+
     _database.getMessagesStream(conversationId).listen((messagesList) {
-      var latest = messagesList.first.timestamp;
-      final newList = <MessagesListItem>[SectionDate(latest)];
+      var latest = DateTime.fromMicrosecondsSinceEpoch(0); // init to minimum
```
Comment (nickmeinhold) [inline lib/services/database_service.dart:30]: Correct me if I'm wrong - this change has nothing to do with bug right?  If you'd like to make the change can it go up as it's own issue/PR so it can be discussed?

Comment (gaslitbytech) [reply lib/services/database_service.dart:30]: I’ll create the Additional issue.

Comment (gaslitbytech) [reply lib/services/database_service.dart:30]: I added #208 to track this issue / solution separately.

**Comment by gaslitbytech** [comment]
> My suggestion would be that we take the time to talk it through

Happy with that though I this talk shouldn't delay this PR as this issue makes it hard / impossible to use this app.

**Comment by nickmeinhold** [comment]
Fair enough, I’ll revert the PR - it shouldn’t have gone up without tests I suppose, I created issues to track making tests but that was probably a bad idea.

**Comment by gaslitbytech** [comment]
Don't think we should revert. I like the idea of separate issues. Though yes need to act on them this week.

**Review by nickmeinhold — APPROVED** [review]
Thanks for figuring this out with me @tourdownunder - great to be working on this with you
